version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: false
      - run:
          name: Build image
          command: |
            docker build -t laudspeaker --build-arg="EXTERNAL_URL=$EXTERNAL_URL" --build-arg="FRONTEND_SENTRY_AUTH_TOKEN=$FRONTEND_SENTRY_AUTH_TOKEN" --build-arg="BACKEND_SENTRY_AUTH_TOKEN=$BACKEND_SENTRY_AUTH_TOKEN" --build-arg="REACT_APP_POSTHOG_HOST=$REACT_APP_POSTHOG_HOST" --build-arg="REACT_APP_POSTHOG_KEY=$REACT_APP_POSTHOG_KEY" --build-arg="REACT_APP_ONBOARDING_API_KEY=$REACT_APP_ONBOARDING_API_KEY" -f Dockerfile .
      - run:
          name: Save image as tar
          command: |
            mkdir -p images
            docker image save -o "images/laudspeaker" "laudspeaker"
      - persist_to_workspace:
          root: .
          paths:
            - images
  push:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: false
      - run: # https://circleci.com/docs/env-vars/#example-configuration-of-environment-variables
          name: "Setup custom environment variables"
          command: |
            echo 'export IMAGE_NAME="jaredhanson11/laudspeaker-test"' >> "$BASH_ENV"
            echo 'export IMAGE_TAG="${CIRCLE_SHA1:0:20}"' >> "$BASH_ENV"
      - run:
          name: Load image
          command: |
            docker image load < "images/laudspeaker"
      - run:
          name: Tag image with appropriate tags
          command: |
            docker image tag laudspeaker ${IMAGE_NAME}:${IMAGE_TAG}
            docker image tag laudspeaker ${IMAGE_NAME}:latest
      - run:
          name: Push tagged images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ${IMAGE_NAME}:latest
            docker push ${IMAGE_NAME}:${IMAGE_TAG}
workflows:
  build_and_push_staging:
    jobs:
      - build:
          filters:
            branches:
              only:
                - jared/cypress
      - push:
          filters:
            branches:
              only:
                - jared/cypress
