name: Build, test, push, deploy staging on commit
on:
  push:
    branches:
      - jared/cypress
jobs:
  setup:
    name: Setup variables
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.short_sha.outputs.short_sha }}
    steps:
      - id: short_sha
        run: |
          SHA=${{ github.sha }} 
          echo short_sha=${SHA:0:20} >> "$GITHUB_OUTPUT"
  build-staging:
    needs: [setup]
    name: Build docker image
    uses: ./.github/workflows/actions/build.yml
    secrets: inherit
    with:
      dockerfile: Dockerfile.ghtest
      output: laudspeaker
      external_url: app-staging.laudspeaker.com
  test-staging:
    needs: [setup, build-staging]
    name: Test docker image
    uses: ./.github/workflows/actions/test.yml
    with:
      image: laudspeaker
  push-staging:
    needs: [setup, test-staging]
    name: Tag and push docker images
    uses: ./.github/workflows/actions/push.yml
    with:
      image: laudspeaker
      tags: jaredhanson11/laudspeaker:latest,jaredhanson11/laudspeaker:${{ needs.setup.outputs.short_sha }}
    secrets: inherit
