name: Build, test, push, deploy staging on commit
on:
  push:
    branches:
      - jared/cypress
jobs:
  build-staging:
    name: Build docker image
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      dockerfile: Dockerfile
      output: laudspeaker
      external_url: app-staging.laudspeaker.com
  # test-staging:
  #   name: Test docker image
  #   uses: ./.github/workflows/test.yml
  #   with:
  #     input: laudspeaker
  push-staging:
    name: Tag and push docker images
    uses: ./.github/workflows/push.yml
    with:
      input: laudspeaker
      tags: jaredhanson11/laudspeaker:latest # ,jaredhanson11/laudspeaker:${{ env.SHORT_SHA }}
    secrets: inherit
