name: Trigger perf test
on:
  workflow_dispatch:
    inputs:
      endpoint:
        description: Endpoint url
        type: string
        required: true
        default: https://perf.laudspeaker.com
      csv:
        description: CSV url
        type: string
        required: true

jobs:
  trigger-perf-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download csv
        id: csv
        run: |
          env
          export CSV_FILEPATH=${GITHUB_WORKSPACE}/test.csv
          echo "CSV_FILEPATH=${CSV_FILEPATH}" >> "$GITHUB_OUTPUT"
          curl ${{ inputs.csv }} -o ${CSV_FILEPATH}
          ls ${GITHUB_WORKESPACE}
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: ./packages/tests/k6/customer_messages_test.js
          flags: --quiet
        env:
          BASE_URL: ${{ inputs.endpoint }}
          CSV_FILEPATH: ${{ steps.csv.outputs.CSV_FILEPATH }}
