name: Trigger perf test
on:
  workflow_dispatch:
    inputs:
      endpoint:
        description: Endpoint url
        type: string
        required: true
        default: https://perf.laudspeaker.com
      test_size:
        description: Test size (# of customers)
        type: choice
        required: true
        default: "1000"
        options:
          - "100"
          - "1000"
          - "10000"
          - "50000"
          - "100000"
          - "500000"
          - "1000000"

jobs:
  trigger-perf-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: kanga333/variable-mapper@master
        name: Setup params
        id: params
        with:
          key: "${{ inputs.test_size }}"
          map: |
            {
              "^100$": {
                  "CSV_URL": "https://testtachyontest123.s3.us-west-1.amazonaws.com/perf-folder/perf-100.csv",
                  "NUM_CUSTOMERS": "100",
                  "POLLING_MINUTES": ".1"
              },
              "^1000$": {
                  "CSV_URL": "https://testtachyontest123.s3.us-west-1.amazonaws.com/perf-folder/perf-1000.csv",
                  "NUM_CUSTOMERS": "1000",
                  "POLLING_MINUTES": ".5"
              },
              "^10000$": {
                  "CSV_URL": "https://testtachyontest123.s3.us-west-1.amazonaws.com/perf-folder/perf-10000.csv",
                  "NUM_CUSTOMERS": "10000"
              },
              "^50000$": {
                  "CSV_URL": "https://testtachyontest123.s3.us-west-1.amazonaws.com/perf-folder/perf-50000.csv",
                  "NUM_CUSTOMERS": "50000"
              },
              "^100000$": {
                  "CSV_URL": "https://testtachyontest123.s3.us-west-1.amazonaws.com/perf-folder/perf-100000.csv",
                  "NUM_CUSTOMERS": "100000"
              },
              "^500000$": {
                  "CSV_URL": "https://testtachyontest123.s3.us-west-1.amazonaws.com/perf-folder/perf-500000.csv",
                  "NUM_CUSTOMERS": "500000"
              },
              "^1000000$": {
                  "CSV_URL": "https://testtachyontest123.s3.us-west-1.amazonaws.com/perf-folder/perf-1000000.csv",
                  "NUM_CUSTOMERS": "1000000"
              },
              ".*": {
                  "POLLING_MINUTES": "1"
              }
            }
          export_to: output,log
          mode: fill
      - name: Download csv
        id: csv
        run: |
          export CSV_FILEPATH=${GITHUB_WORKSPACE}/test.csv
          echo "CSV_FILEPATH=${CSV_FILEPATH}" >> "$GITHUB_OUTPUT"
          curl ${{ steps.params.outputs.CSV_URL }} -o ${CSV_FILEPATH}
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: ./packages/tests/k6/customer_messages_test.js
          flags: --quiet
        env:
          BASE_URL: ${{ inputs.endpoint }}
          CSV_FILEPATH: ${{ steps.csv.outputs.CSV_FILEPATH }}
          NUM_CUSTOMERS: ${{ steps.params.outputs.NUM_CUSTOMERS }}
          POLLING_MINUTES: ${{ steps.params.outputs.POLLING_MINUTES }}
